# Generated by Django 4.1.4 on 2023-05-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book_md',
        ),
    ]
