# Generated by Django 4.1.4 on 2023-05-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_book_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_md',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
