# Generated by Django 4.1.4 on 2023-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_md_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_md',
            name='publication_date',
            field=models.DateField(default=None),
        ),
    ]
